import { fetchJson } from '../core/http.js';
import { mockTickers } from '../core/mock.js';
import { buildSigningPreview, signSodexAction } from './sodexSigning.js';

const resourcePath = {
  tickers: ['/markets/tickers24hr', '/markets/tickers'],
  symbols: ['/markets/symbols', '/symbols'],
  klines: ['/markets/klines'],
  orderbook: ['/markets/orderbook'],
  markPrices: ['/markets/mark-prices']
};

function normalizeTicker(item) {
  return {
    symbol: item.symbol || item.instID || item.name || 'UNKNOWN',
    last: String(item.last || item.lastPrice || item.price || item.close || '0'),
    change24h: String(item.change24h || item.priceChangePercent || item.changePercent || '0'),
    volume24h: String(item.volume24h || item.volume || item.quoteVolume || '0'),
    bid: String(item.bid || item.bestBid || '0'),
    ask: String(item.ask || item.bestAsk || '0')
  };
}

function unwrap(payload) {
  if (Array.isArray(payload)) return payload;
  if (Array.isArray(payload?.data)) return payload.data;
  if (Array.isArray(payload?.data?.list)) return payload.data.list;
  if (Array.isArray(payload?.result)) return payload.result;
  return payload;
}

export function sodexClient(cfg) {
  const spotBase = cfg.spotBaseUrl.replace(/\/$/, '');
  const perpsBase = cfg.perpsBaseUrl.replace(/\/$/, '');
  const baseFor = market => market === 'spot' ? spotBase : perpsBase;

  async function get(market = 'perps', resource = 'tickers', params = {}) {
    if (cfg.mockMode) return { ok: false, fallback: true, data: mockTickers, source: 'mock:sodex' };
    const paths = resourcePath[resource] || resourcePath.tickers;
    let last;
    for (const path of paths) {
      const query = new URLSearchParams();
      for (const [key, value] of Object.entries(params)) if (value !== undefined && value !== '') query.set(key, value);
      const url = `${baseFor(market)}${path}${query.size ? `?${query}` : ''}`;
      const result = await fetchJson(url, { ttlMs: 20_000, fallback: null }).catch(error => ({ ok: false, error: String(error.message || error), data: null, source: url }));
      if (result.ok) return result;
      last = result;
    }
    return { ok: false, fallback: true, data: mockTickers, source: last?.source || 'mock:sodex', error: last?.error || 'All SoDEX paths failed' };
  }

  return {
    async tickers(market = 'perps') {
      const result = await get(market, 'tickers');
      const list = unwrap(result.data);
      result.data = Array.isArray(list) ? list.map(normalizeTicker) : mockTickers;
      return result;
    },
    async symbols(market = 'perps') {
      return get(market, 'symbols');
    },
    async markPrices() {
      return get('perps', 'markPrices');
    },
    async accountState(userAddress) {
      if (!userAddress) return { ok: false, data: { message: 'SODEX_USER_ADDRESS missing' }, fallback: true, source: 'config' };
      const url = `${perpsBase}/accounts/${userAddress}/state`;
      return fetchJson(url, { ttlMs: 10_000, fallback: { balances: [], positions: [] } });
    },
    async paperOrder(order) {
      const price = Number(order.price || order.last || 0) || 0;
      const quantity = Number(order.quantity || 0);
      return {
        id: `paper_${Date.now()}_${Math.random().toString(16).slice(2, 8)}`,
        mode: 'paper',
        status: 'accepted',
        symbol: order.symbol,
        side: order.side,
        orderType: order.orderType || 'market',
        quantity,
        notional: +(price * quantity).toFixed(2),
        price,
        createdAt: new Date().toISOString(),
        rationale: order.rationale || 'Generated by SoDEX SignalOS signal engine.'
      };
    },
    async signingPreview(order = {}) {
      const market = order.market === 'spot' ? 'spot' : 'perps';
      const params = {
        accountID: Number(cfg.accountId || 0),
        symbolID: Number(order.symbolID || 1),
        orders: [{
          clOrdID: order.clientOrderId || `demo-${Date.now()}`,
          modifier: Number(order.modifier || 1),
          side: String(order.side || 'buy').toLowerCase() === 'sell' ? 2 : 1,
          type: String(order.orderType || 'market').toLowerCase() === 'limit' ? 1 : 2,
          timeInForce: Number(order.timeInForce || 3),
          ...(order.price ? { price: String(order.price) } : {}),
          quantity: String(order.quantity || '0'),
          reduceOnly: Boolean(order.reduceOnly || false),
          positionSide: Number(order.positionSide || 1)
        }]
      };
      return buildSigningPreview({ cfg, market, actionType: 'newOrder', params });
    },
    async liveOrder(order = {}) {
      const preview = await this.signingPreview(order);
      if (!cfg.liveTrading) {
        return { ok: false, blocked: true, message: 'Live trading is disabled. Paper mode is safe for judging/demo. Set SODEX_LIVE_TRADING=true only after rotating leaked keys and funding testnet intentionally.', signingPreview: preview };
      }
      const market = order.market === 'spot' ? 'spot' : 'perps';
      const params = preview.payload.params;
      const signed = await signSodexAction({ cfg, market, actionType: 'newOrder', params });
      if (!signed.ok) return { ok: false, blocked: true, message: signed.error, signingPreview: preview };
      return { ok: false, blocked: true, message: 'Signed payload generated, but HTTP live send is intentionally blocked in this build. Review headers/body, nonce manager, and risk controls before enabling submission to SoDEX.', signedRequest: { ...signed, signature: '<redacted>', headers: { ...signed.headers, 'X-API-Sign': '<redacted>' } } };
    }
  };
}
